"use strict";

const Msg = {
    SUCCESS_MESSAGE: "Success",
    EMAIL_ALREADY_EXIST: "Email already exist",
    LOGIN_SUCCESSFULLY: "Login successfully",
    SIGNUP_SUCCESSFULLY: "Signup successfully",
    TOKEN_REQUIRED: "Token required",
    LOGIN_ALREADY: "Already logged in",
    LOGIN_REQUIRED: "Login required",
    TOKEN_INVALID: "Token invalid",
    INVALID_PAGE_NUMBER: "Invalid page number",
    EMAIL_IS_REQUIRED: "Email is required",
    EMAIL_NOT_EXIST: "Email not exist",
    EMAIL_ALREADY_VERIFIED: "Email already verified",
    EMAIL_SUCCESSFULLY_VERIFIED: "Email verified successfully",
    INVALID_EMAIL: "Invalid email",
    PASSWORD_IS_REQUIRED: "Password is required",
    CONFIRM_PASSWORD_IS_REQUIRED: "Confirm Password is required",
    PASSWORD_DOES_NOT_MATCH: "Password and confirm password does not match.",
    NEW_PASSWORD_IS_REQUIRED: "New password is required",
    NAME_IS_REQUIRED: "Name is required",
    FIRST_NAME_IS_REQUIRED: "First Name is required",
    LAST_NAME_IS_REQUIRED: "Last Name is required",
    PHONE_IS_REQUIRED: "Phone is required",
    PHONE_LENGTH_IS_REQUIRED: "Phone should contain 10 digit",
    TYPE_IS_REQUIRED: "Type is required",
    ADDRESS_IS_REQUIRED: "Address is required",
    COUNTRY_IS_REQUIRED: "Country is required",
    POSTCODE_IS_REQUIRED: "Postcode is required",
    COMPANY_NAME_IS_REQUIRED: "Company name is required",
    PROFESSIONAL_CATEGORY_IS_REQUIRED: "Professional category is required",
    INVALID_LOGIN_CREDENTIAL: "Invalid login credential",
    YOUR_ACCOUNT_SUSPENDED: "Your account has been temporarily suspended. Please contact administrator.",
    INVALID_PASSWORD: "Invalid password",
    EMAIL_SENT_SUCCESSFULLY: "Password has been sent on your registered email!",
    RESET_PASSWORD_EMAIL_SENT_SUCCESSFULLY: "Reset password link sent to your registered email.",
    EMAIL_NOT_SEND: "Email not send",
    FILE_IS_REQUIRED: "Promotion file is required",
    PROMOTION_ID_IS_REQUIRED: "Promotion id is required",
    LOGO_ID_IS_REQUIRED: "Logo id is required",
    INVALID_PROMOTION_ID: "Invalid promotion id",
    INVALID_LOGO_ID: "Invalid logo id",
    PROMOTION_NAME_ALREADY_EXIST: "Promotion already exist",
    PROMOTION_ADDED_SUCCESSFULLY: "Promotion has been added successfully!",
    PROMOTION_UPDATED_SUCCESSFULLY: "Promotion has been updated successfully!",
    LOGO_ADDED_SUCCESSFULLY: "Promotion has been added successfully!",
    USER_ID_IS_REQUIRED: "User id is required",
    INVALID_USER_ID: "Invalid user id",
    LINK_EXPIRED: "Reset password link is expired.",
    USER_NOT_FOUND: "User not found",
    SUBJECT_IS_REQUIRED: "Subject is required",
    MESSAGE_IS_REQUIRED: "Message is required",
    CONTACT_ADDED_SUCCESSFULLY: "Contact has been submitted successfully!",
    IMAGE_IS_REQUIRED: "Promotion Image is required",
    INVALID_FILE_TYPE: "Invalid promotion file",
    INVALID_IMAGE_TYPE: "Invalid promotion image",
    INVALID_CURRENT_PASSWORD: "Invalid current password",
    USER_UPDATE_SUCCESSFULLY: "Detail has been updated successfully!",
    PASSWORD_UPDATE_SUCCESSFULLY: "Password has been changed successfully!",
    ACCOUNT_DELETE_SUCCESSFULLY: "Account has been deleted successfully!",
    LOGOUT_SUCCESSFUL: "You have been logged out successfully",
    PROFILE_UPDATE_SUCCESSFULLY: "Detail has been updated successfully!",
    BACKGROUND_ID_IS_REQUIRED: "Background id is required",
    INVALID_BACKGROUND_ID: "Invalid Background id",
    HEADER_ID_IS_REQUIRED: "Header id is required",
    INVALID_HEADER_ID: "Invalid Header id",
    BACKGROUND_ADDED_SUCCESSFULLY: "Background has been added successfully!",
    BACKGROUND_NOT_FOUND: "Background not found",
    STATUS_UPDATE_SUCCESSFULLY: "Status has been updated successfully!",
    BACKGROUND_DELETE_SUCCESSFULLY: "Background has been deleted successfully!",
    HEADER_LOGO_IS_REQUIRED: "Header logo is required",
    INVALID_FILE_TYPE_HEADER_LOGO: "Invalid header logo file type",
    HEADER_ADDED_SUCCESSFULLY: "Header has been added successfully!",
    HEADER_UPDATED_SUCCESSFULLY: "Header has been updated successfully!",
    HEADER_NOT_FOUND: "Header not found",
    HEADER_DELETE_SUCCESSFULLY: "Header has been deleted successfully!",
    LOGO_ADDED_SUCCESSFULLY: "Logo has been added successfully!",
    LOGO_DELETE_SUCCESSFULLY: "Logo has been deleted successfully!",
    LOGO_NOT_FOUND: "Logo not found",
    LOGO_ID_IS_REQUIRED: "Logo id is required",
    LOGO_BACKGROUND_ID: "Invalid logo id",
    PROMOTION_ID_IS_REQUIRED: "Promotion id is required",
    INVALID_PROMOTION_ID: "Invalid promotion id",
    PROMOTION_DELETE_SUCCESSFULLY: "Promotion has been deleted successfully!",
    USER_DELETE_SUCCESSFULLY: "User has been deleted successfully!",
    USER_ADD_SUCCESSFULLY: "User has been added successfully!",
    USER_LIST_SUCCESSFULLY: "User list successfully!",
    PROFILE_UPDATE_SUCCESSFULLY: "Profile has been updated successfully!",
    SOMETHING_WENT_WRONG: "Something went wrong!",
    UNAUTHORIZED: "UnAuthorized",
    NAME_ALREADY_EXIST: "Name already exist",
    DELETE_SUCCESSFULLY: "Delete successfully",
    EMAIL_ALREADY_EXIST: "Email already exist",
    USER_ALREADY_EXIST: "User already exist",
    STATUS_IS_REQUIRED: "Status is required",
    INVALID_STATUS: "Invalid Status",
    HEADER_VARIANT_IS_REQUIRED: "Header Variant is required",
    INVALID_HEADER_VARIANT: "Invalid Header Variant",
    CONTACT_ID_IS_REQUIRED: "Contact id is required",
    INVALID_CONTACT_ID: "Invalid Contact id",
    CONTACT_DELETE_SUCCESSFULLY: "Contact has been deleted successfully!",
    CODE_IS_REQUIRED: "Code is required",
    NAME_IS_REQUIRED: "Name is required",
    CONTENT_IS_REQUIRED: "Content is required",
    ID_IS_REQUIRED: "ID is required",
    INVALID_ID: "Invalid ID",
    CODE_ALREADY_EXIST: "Code already exist",
    ACCOUNT_VERIFY: "Account verify",
    NBC_ADD_SUCCESSFULLY: "Nbc add successfully",
    NBC_NOT_FOUND: "Nbc not found",
    NBC_UPDATE_SUCCESSFULLY: "Nbc updated successfully",
    NBC_DELETE_SUCCESSFULLY: "Nbc deleted successfully",
    NBC_IS_REQUIRED: "nbc is required",
    ECPOINTS_IS_REQUIRED: "ecPoints is required",
    REGION_CODE_IS_REQUIRE: "Region code is required",
    REGION_TITLE_IS_REQUIRE: "Region title is required",
    TITLE_IS_REQUIRE: "Title is required",
    REGIONS_ADD_SUCCESSFULLY: "Regions add successfully",
    REGIONS_NOT_FOUND: "Regions not found",
    REGIONS_UPDATE_SUCCESSFULLY: "Regions updated successfully",
    REGIONS_DELETE_SUCCESSFULLY: "Regions deleted successfully",
    WEATHER_STATION_ADD_SUCCESSFULLY: "Weather station add successfully",
    WEATHER_STATION_UPDATE_SUCCESSFULLY: "Weather station add successfully",
    WEATHER_UPDATE_SUCCESSFULLY: "Weather updated successfully",
    WEATHER_STATION_NOT_FOUND: "Weather not found",
    WEATHER_DELETE_SUCCESSFULLY: "Regions deleted successfully",
    ADMIN_ADD_SUCCESSFULLY: "Admin add successfully",
    ADMIN_NOT_FOUND: "Admin not found",
    ADMIN_UPDATE_SUCCESSFULLY: "Admin updated successfully",
    ADMIN_DELETE_SUCCESSFULLY: "Admin deleted successfully",
    AUDITOR_DOCUMENT_NOT_FOUND: "Auditor document not found",
    AUDITOR_DOCUMENT_VERIFY_SUCCESSFULLY: "Auditor document verify successfully",
    AUDITOR_DOCUMENT_UNVERIFIED_SUCCESSFULLY: "Auditor document unverified successfully",

    SITE_SETTINGS_UPDATE_SUCCESSFULLY: "Site settings updated successfully",

    AUDIT_ID_IS_REQUIRED: "Audit ID is required",
    REASON_IS_REQUIRED: "Reason for rejection is required",

    PRODUCT_DELETE_SUCCESSFULLY: "Product has been deleted successfully!",
    PRODUCT_ADD_SUCCESSFULLY: "Product has been added successfully!",
    PRODUCT_LIST_SUCCESSFULLY: "Product list successfully!",
    PRODUCT_UPDATE_SUCCESSFULLY: "Product detail has been updated successfully!",
    INVALID_IMPORT_FILE: "Invalid Import file. File should be Save the file as an Excel Workbook",
    PRODUCT_IMPORT_SUCCESSFULLY: "Products has been imported successfully!",
    REQUIRED_IMPORT_FILE: "Required Import file.",


    RECORD_DELETE_SUCCESSFULLY: "Record has been deleted successfully!",
    RECORD_ADD_SUCCESSFULLY: "Record has been added successfully!",
    RECORD_LIST_SUCCESSFULLY: "Record list successfully!",
    RECORD_UPDATE_SUCCESSFULLY: "Record detail has been updated successfully!",
    RECORD_NOT_FOUND: "Record not found",

    PROJECT_NAME_IS_REQUIRED: "Project name is required",
    PROVINCE_ID_IS_REQUIRED: "Province id is required",
    PROVINCE_IS_REQUIRED: "Province is required",
    CITY_IS_REQUIRED: "City is required",
    WEATHER_STATION_ID_IS_REQUIRED: "Weather Station id is required",
    HDD_IS_REQUIRED: "Hdd is required",
    NBCCLIMATEZONE_IS_REQUIRED: "Nbc Climate Zone is required",
    NBC_PERSPECTIVE_TIER_ID_IS_REQUIRED: "Nbc perspective tier id is required",
    HOUSETYPEID_IS_REQUIRED: "House Type id is required",
    FDWRPERCENT_IS_REQUIRED: "fdwr percent is required",
    VOLUME_IS_REQUIRED: "Volume is required",
    CREDIT_IS_REQUIRED: "credit is required",
    ECP_IS_REQUIRED: "ECP Required is required",
    ASSEMBLY_IS_REQUIRED: "Assembly is required",
    WEATHER_STATION_IS_REQUIRED: "Weather station not found",
    AUDIT_NOT_FOUND: "Invalid auditId,Audit not found",
    AUDITOR_CAN_UPDATE_STATUS: "Only auditor can update status",
    USER_IS_NOT_AUDITOR: "Only auditor create the audit",
    TOTAL_ECP_LESS_THEN_REQUIRED_ECP: "The total ECP is less than the required ECP",
    SELECTED_ASSEMBLY_MUST_ARRAY: "selectedAssembly must be an array",
    INVALID_FORMAT_SELECTED_ASSEMBLY: "Invalid format for selectedAssembly",
    INVALID_ASSEMBLY_ID: "Invalid assemblyId",
    CREATE_AUDIT_SUCCESS: "We Successfully generated your energy conservation points result reports based on your Audit.",
    UPDATE_PROFILE_PINCODE: "Please update the pincode in your profile",
    CREATE_AUDIT_REQUEST_SUCCESS: "Your audit request is created successfully.",
    AUDIT_REQUEST_ALREADY_EXIST: "Your audit request already exist AND it's in progress",
    PINCODE_REQUIRED: "Pincode is required",
    PINCODE_IS_EXIST: "Pincode is already exist",
    PROVINCE_IS_EXIST: "Province is already exist",
    PINCODE_ADDED_SUCCESS: "Pincode added successfully",
    PROVINCE_ADDED_SUCCESS: "Province added successfully",
    CANT_START_OTHER_AUDITOR_AUDIT: "This audit is accepted by another auditor so you can't update this audit.",
    AUDIT_IS_ALREADY_START: "Audit is already started",
    AUDIT_IS_START: "Audit is started now",
    NOT_AUDITOR: "You are not auditor",
    CREATE_LEADS_SUCCESS: "We Successfully sent your inquiry",
    LEAD_CONNECTED: "Lead connected successfully",
    LEAD_REJECTED: "Lead rejected!",
    CREATE_PROPERTY_SUCCESS: "Property created successfully",
}
module.exports = {
    Msg
}